### ISSUE TITLE
Does it work with CSP `unsafe-eval`?

### ISSUE THREAD

**Issue by silverwind** [hyperjump-io/json-schema#35]
Does this module would work with [`unsafe-eval`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions)?

If it does, this info should be added as a feature in the README, because it would be a major benefit compared to similar modules which require `unsafe-eval`, like these ones:

- ajv: https://github.com/ajv-validator/ajv/issues/406
- schemasafe: https://github.com/ExodusMovement/schemasafe/issues/153

**Comment by jdesrosiers** [comment]
I haven't actually tried it myself, but there's no reason this package shouldn't work with `unsafe-eval`. There's no code that evaluates strings as JavaScript anywhere in this package.

**Comment by silverwind** [comment]
Right, that sounds promising. If there are none of the 5 constructs mentioned on MDN in the codebase, you can be sure it will work.

**Comment by jdesrosiers** [comment]
I can confirm that none of those 5 constructs are used.

**Comment by silverwind** [comment]
Good enough for me, thanks 👍.
