### ISSUE TITLE
Typescript error while importing from `@hyperjump/json-schema/experimental`

### ISSUE THREAD

**Issue by GabenGar** [hyperjump-io/json-schema#38]
When building I get this error:
```
error TS2307: Cannot find module '@hyperjump/json-schema/experimental' or its corresponding type declarations.
```
Reproduction:
```sh
git clone https://github.com/GabenGar/repros
cd ./repros/json-schema-experimental-module
npm install
npm run build
```

It is an issue with type definitions because vanilla js file works fine.

**Comment by jdesrosiers** [comment]
This package uses the package.json "exports" field. [TypeScript understands "exports"](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#packagejson-exports-imports-and-self-referencing), but you need to change a couple settings in your `tsconfig.json` for it to work.

```
    "module": "Node16",
    "moduleResolution": "Node16",
```

or

```
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
```

This is probably something that would be helpful to add to the README.

**Comment by GabenGar** [comment]
Okay, I've tried with these options and it does work. The issue however is I encountered the problem while working on a `Next.js` project and afaik it has some problems consuming "true" ESM code, so switching these flags is not so trivial. But it' not a problem of this package.
