### ISSUE TITLE
Could not resolve "@hyperjump/browser" after upgrading from 1.6.7 to 1.7.1

### ISSUE THREAD

**Issue by xhuberdeau** [hyperjump-io/json-schema#47]
Hello,

Thanks for this repo :slightly_smiling_face:.

As the title says, after upgrading from 1.6.7 to 1.7.1, I get the error `Could not resolve "@hyperjump/browser"` when building my node backend app with esbuild.
Is it expected?

Thanks.

**Comment by jdesrosiers** [comment]
In 1.7.0, some of the functionality in `@hyperjump/json-schema` was extracted into a component that can be reused for other purposes. That new component is `@hyperjump/browser`. `@hyperjump/browser` is included in `package.json` as a peer dependency. Perhaps esbuild is handling peer dependencies in an unexpected way? I'll look into it.

**Comment by jdesrosiers** [comment]
It looks like esbuild works fine. Are you using `yarn`? After some poking around, I found out that `yarn` doesn't install peer dependencies automatically like `npm`. So if you're using `yarn`, you'll need to add `@hyperjump/browser` to your `package.json`.

**Comment by xhuberdeau** [comment]
Hello, yes I'm using Yarn. Thanks for your fast reply :slightly_smiling_face:
