### ISSUE TITLE
Cannot use validation in background scripts/service workers of browser extensions

### ISSUE THREAD

**Issue by frederikb** [hyperjump-io/json-schema#48]
Hi,

I would like to use your library in the context of a browser extension for Chrome/Firefox built using the Web Extensions API.

The main logic of the extension is run in a so-called background script. In Manifest V3 versions of that API these are executed using [service workers](https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers). The main impact is of course that we do not have a reference to the DOM and the `document` global variable is undefined.

When running the following code in this context I unfortunately get an exception because it assumes a normal web browser context:
```javascript
const BOOKMARK_SCHEMA_URI = 'https://raw.githubusercontent.com/frederikb/bookmarksync/main/src/utils/bookmark.schema.json';
registerSchema(bookmarkSchema); // this is a parsed JSON containing the schema with a `$id` defined matching the uri
const validator = await validate(BOOKMARK_SCHEMA_URI);
```
The error:
> ReferenceError: document is not defined
        at contextUri (background.js:13617:46)
        at get (background.js:13620:69)
        at getSchema (background.js:13701:26)
        at validate

The stacktrace is a bit mangled due to not having source maps set up, but the gist of it is that it's failing in [@hyperjump/browser:](https://github.com/hyperjump-io/browser/blob/main/lib/browser/context-uri.browser.js)
```javascript
export const contextUri = () => document.location.toString();
```
while attempting to determine `baseUri` because it assumes a browser context.

My schema does not have any references to external schemas, neither absolute nor relative to.

1. Is running in a web/service worker supposed to work and I'm doing some wrong?
2. If not, is this something you are interested in supporting?
3. Is there a workaround you would suggest? I could probably stub out the global document, but with what kind of location?

Thanks!

**Comment by jdesrosiers** [comment]
That's an interesting case. I hadn't considered service workers. I'll work on it. I expect that verifying that it works will be harder than the fix itself.

**Comment by jdesrosiers** [comment]
> I could probably stub out the global document, but with what kind of location?

That would work. If you stub out the location to just an empty string, it should work fine. Ultimately, the feature that code supports doesn't make sense in the context of service workers, so whatever you need to do to make it not blow up shouldn't hurt anything else you're trying to use the library for.

**Comment by jdesrosiers** [comment]
I published a fix that I think should work. Let me know if you have you problems.

**Comment by frederikb** [comment]
Thanks @jdesrosiers for the fast turnaround! I can happily confirm that I can validate files using a schema embedded in my codebase.

Enjoying your libary so far, thanks a lot!

**Comment by jdesrosiers** [comment]
Glad it's working out for you!
