### ISSUE TITLE
Regular expression parsing failure

### ISSUE THREAD

**Issue by mellster2012** [hyperjump-io/json-schema#51]
```
"valueDecimal": {
"description": "The actual value to for an initial answer.",
"pattern": "^-?(0|[1-9][0-9]{0,17})(\\.[0-9]{1,17})?([eE][+-]?[0-9]{1,9}})?$",
"type": "number"
}
```

validate fails with: SyntaxError: Invalid regular expression: /^-?(0|[1-9][0-9]{0,17})(\.[0-9]{1,17})?([eE][+-]?[0-9]{1,9}})?$/: Lone quantifier brackets at new RegExp (<anonymous>)

**Comment by mellster2012** [comment]
[fhir.schema.json](https://github.com/hyperjump-io/json-schema/files/14389672/fhir.schema.json)

**Comment by mellster2012** [comment]
Actually that's a real mistake in their schema, the regexp does have a lone closing bracket at the end - closing.

**Comment by jdesrosiers** [comment]
Glad you figured it out. I see the FHIR schema is still a disaster zone. The `pattern` keyword doesn't even apply to numbers, so all they've accomplished is shooting themselves in the foot. The should have used `$comment` instead.
