### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by tomsfernandez** [hyperjump-io/json-schema#6]
Hi! Any chance of supporting YAML validations of a json schema?

**Comment by jdesrosiers** [comment]
Yes, it's on the roadmap. Since you asked, I'll see about moving up in priority.

**Comment by jawaff** [comment]
Are there still plans for YAML support or has this been forgotten about?

**Comment by jdesrosiers** [comment]
It's not forgotten, it just hasn't been a high enough priority. My main concern is that the YAML parser is enormous compared to this library and I don't want to require that as a dependency for people who aren't concerned with YAML. I need to research how to make a dependency optional.

**Comment by jdesrosiers** [comment]
I just added support for custom media type plugins that you can use to configure support for YAML. Instructions are in the README, https://github.com/hyperjump-io/json-schema-validator#media-types.

**Comment by jawaff** [comment]
That'll work. Thanks for the update.
