### ISSUE TITLE
`JsonSchema` `boolean` type

### ISSUE THREAD

**Issue by silverwind** [hyperjump-io/json-schema#62]
Is there a reason why the`JsonSchema` type has a `boolean` in its union type? As far as I'm aware, booleans are not valid JSON schemas.

https://github.com/hyperjump-io/json-schema/blob/724e2434459ecedb089cd9e8e2b309802cc6b5fe/stable/index.d.ts#L5

**Comment by jdesrosiers** [comment]
A boolean is a valid JSON Schema since draft-06. You can use a boolean anywhere a schema is expected.

**Comment by silverwind** [comment]
Found a way:

```ts
type JsonSchemaObject = Exclude<JsonSchema, boolean>;

**Comment by jdesrosiers** [comment]
That's a great solution.

**Comment by silverwind** [comment]
Yeah, but it's only a temporary solution of course. I will make my code work with boolean schemas :)
