### ISSUE TITLE
Bundling schema with urn ID does not replace urn $ref

### ISSUE THREAD

**Issue by andlbrei** [hyperjump-io/json-schema#63]
Hi,

I'm trying to bundle a schema with urn identifiers.
I added the urn plugin for `@hyperjump/browser` based on [the example](https://github.com/hyperjump-io/browser/#uri-schemes).
The external schema (Address) is added to `$defs` in the resulting schema, but the `$ref` is not changed to refer to `$defs`.
What am I doing wrong?

Combining the two following schemas:

```json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "urn:test:something/schemas/CompanyCertificate",
	"type": "object",
	"title": "Company Certificate",
	"description": "It's the Company Certificate",
	"properties": {
		"companyInformation": {
			"type": "object",
			"properties": {
				"businessAddress": {
					"$ref": "urn:test:something/schemas/Address"
				}
			}
		}
	}
}
```

```json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "urn:test:something/schemas/Address",
	"type": "object",
	"required": ["addressLine1", "postalCode", "postalPlace"],
	"properties": {
		"addressLine1": {
			"type": "string"
		},
		"postalCode": {
			"type": "string"
		},
		"postalPlace": {
			"type": "string"
		}
	}
}

```

With this code:
```js
addUriSchemePlugin("urn", {
  parse: (urn, baseUri) => {
    let { nid, nss, query, fragment } = parseUrn(urn);
    nid = nid.toLowerCase();

    if (!mappings[nid]?.[nss]) {
      throw Error(`Not Found -- ${urn}`);
    }

    let uri = mappings[nid][nss];
    uri += query ? `?${query}` : "";
    uri += fragment ? `#${fragment}` : "";

    return retrieve(uri, baseUri);
  },
});

registerSchema(schema);
registerSchema(Address);

const bundledSchema = await bundle(
  "urn:test:something/schemas/CompanyCertificate"
);
```

Results in this:

```json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"title": "Company Certificate",
	"description": "It's the Company Certificate",
	"properties": {
		"companyInformation": {
			"type": "object",
			"properties": {
				"businessAddress": { "$ref": "urn:test:something/schemas/Address" }
			}
		}
	},
	"$defs": {
		"Address": {
			"$id": "Address",
			"type": "object",
			"required": ["addressLine1", "postalCode", "postalPlace"],
			"properties": {
				"addressLine1": { "type": "string" },
				"postalCode": { "type": "string" },
				"postalPlace": { "type": "string" }
			}
		}
	}
}

```

Thanks!

**Comment by andlbrei** [comment]
Thanks for the quick reply!

I would have thought that the `$id` would have stayed a URN, or that the `$ref` would change.
Nice to know what the correct behaviour should be.

What I am trying to do is get TypeScript types from my JSON Schema.
[Ajv](https://ajv.js.org/) is used for validating, and it works fine, but it does not have type inference for referenced schemas, which is understandable.
Having schemas defined in separate files is desired, since I will end up with a decent amount of schemas.
These schemas will be used several ways, some dynamically loaded, some might live on a file system, so I figured using URN for `$id` would work fine.
So I already have my schemas defined, and I need to jump through some hoops to get types from them.

I tried using [json-schema-to-typescript](https://github.com/bcherny/json-schema-to-typescript), which uses [json-schema-ref-parser](https://github.com/APIDevTools/json-schema-ref-parser) under the hood to resolve references, but it couldn't find the other schemas, which makes sense as it doesn't have any way of registering schemas, so it can't resolve them based on the URN.
My strategy was then to bundle the schemas using `@hyperjump/json-schema/bundle`, and use the bundled schema to generate the types. 

Running the result schema from my earlier post into `json-schema-to-typescript` gives an error message:
```bash
  stack: 'ResolverError: Error opening file "urn:test:something/schemas/Address" \n' +
    "ENOENT: no such file or directory, open 'urn:test:something/schemas/Address'\n" +
    '    at Object.read (/Users/andersbreilid/workspace/dnb-web-codd-apps/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@11.6.2/node_modules/@apidevtools/json-schema-ref-parser/dist/lib/resolvers/file.js:61:19)',
  code: 'ERESOLVER',
  name: 'ResolverError',
  message: 'Error opening file "urn:test:something/schemas/Address" \n' +
    "ENOENT: no such file or directory, open 'urn:test:something/schemas/Address'",
  source: 'urn:test:something/schemas/Address',
  path: null,
  toJSON: [Function: toJSON],
  ioErrorCode: 'ENOENT',
  footprint: 'null+urn:test:something/schemas/Address+ERESOLVER+Error opening file "urn:test:something/schemas/Address" \n' +
    "ENOENT: no such file or directory, open 'urn:test:something/schemas/Address'",
  toString: [Function: toString]
```

This error is the same as I would get using a non-bundled schema, naturally, as it cannot resolve the URN.
I tried modifying the `$id` to be the full URN, as shown below, but it could still not resolve the reference.
```json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "urn:test:something/schemas/CompanyCertificate",
	"type": "object",
	"title": "Company Certificate",
	"description": "It's the Company Certificate",
	"properties": {
		"companyInformation": {
			"type": "object",
			"properties": {
				"businessAddress": { "$ref": "urn:test:something/schemas/Address" }
			}
		}
	},
	"$defs": {
		"Address": {
			"$id": "urn:test:something/schemas/Address",
			"type": "object",
			"required": ["addressLine1", "postalCode", "postalPlace"],
			"properties": {
				"addressLine1": { "type": "string" },
				"postalCode": { "type": "string" },
				"postalPlace": { "type": "string" }
			}
		}
	}
}
```

They don't seem to be working towards implementing the JSON Schema spec [as indicated in this thread](https://github.com/APIDevTools/json-schema-ref-parser/issues/145), where they state that it is really a OpenAPI 3.0 tool.
(In general there seems to be many tools made for OpenAPI, and many of them lack support for OpenAPI 3.1 and the introduced JSON Schema compatibility.)

You might be correct in that the resulting JSON Schema should work, but I cannot find a tool that can generate types from it, at least not when using URNs.
It seems that I will need to use a different `$id` in order to get types from my schemas.

**Comment by jdesrosiers** [comment]
Yeah, `json-schema-ref-parser` doesn't understand embedded schemas, so this bundler isn't going to help because it's based on the concept of embedded schemas. However, there's a different approach that might work for you.

Instead of using URNs, don't use use `$id` at all and allow the file system path to be schema's identifier. This implementation supports that out-of-the-box and it should work with `json-schema-ref-parser`, which I believe understands file-based references. Ajv doesn't understand file-based references, but you can bundle and then use the result in ajv.

So, I think the following should work in `json-schema-ref-parser`.

`/path/to/schemas/company-certificate.schema.json`
```json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"title": "Company Certificate",
	"description": "It's the Company Certificate",
	"properties": {
		"companyInformation": {
			"type": "object",
			"properties": {
				"businessAddress": {
					"$ref": "./address/schema.json"
				}
			}
		}
	}
}
```

`/path/to/schemas/address.schema.json`
```json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"required": ["addressLine1", "postalCode", "postalPlace"],
	"properties": {
		"addressLine1": {
			"type": "string"
		},
		"postalCode": {
			"type": "string"
		},
		"postalPlace": {
			"type": "string"
		}
	}
}
```

And if you bundle, it should work in ajv.

```javascript
// No registering schemas needed
const bundledSchema =  await bundle("./schemas/company-certificate.schema.json");

// Then load into ajv and validate
```

Or you could use this library to do the validation without needing to bundle.

```javascript
// No registering schemas needed
const result = await validate("./schemas/company-certificate.schema.json", subject);
```

**Comment by andlbrei** [comment]
Thanks, this seems like a good enough solution for now.
I would like to be able to load schemas dynamically without caring about file system references, but I think I can get around it in any case.

Thanks for quick and detailed help!
