### ISSUE TITLE
Validation output does not contain errors and other information after upgrading from 1.7.3 to 1.9.2 

### ISSUE THREAD

**Issue by JeelRajodiya** [hyperjump-io/json-schema#64]
## Output object in version 1.7.3
![image](https://github.com/hyperjump-io/json-schema/assets/63534268/383d7f3c-7b46-4702-9f05-425bb39eb3cf)

## Output Object in version 1.9.2
![image](https://github.com/hyperjump-io/json-schema/assets/63534268/3b3c6151-2b15-433d-80c8-37fefb0a17d3)

I am trying to get the error messages in both the `data validation` and `schema validation`. but after upgrading these field seems to be disappeared. Is there any option I should pass to the validation function to get those error messages? 

## Code for hyperjump 
![image](https://github.com/hyperjump-io/json-schema/assets/63534268/949a1cef-97e3-441b-8b7d-c5854ae54c61)

### Data 
```json
[1,2,3]
```

### Schema 
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
}
```

**Comment by jdesrosiers** [comment]
You get the FLAG output format by default. This format only contains information about whether the validation succeeded or failed. You need to use the BASIC output format to get details about what failed. Previously, the FLAG format was returning some properties that aren't part of the FLAG format. I removed that in the latest release because they don't provide any useful information anyway.

Documentation on how to set the output format is in the [README](https://github.com/hyperjump-io/json-schema?tab=readme-ov-file#output-formats)

**Comment by JeelRajodiya** [comment]
I have was able to produce the errors for the data. But I also wish to produce the errors for the schema itself. as you have mentioned I have set the output format to `BASIC`. please see the code below 

![image](https://github.com/hyperjump-io/json-schema/assets/63534268/fe82bf72-6aa9-446d-9cbf-397b8835c8ed)

I am trying to get errors for the schema as well. for example if the user sets the `type` to `stringg` (which is invalid). I want to point that it is invalid. currently as per my code above hyperjump is throwing `InvalidSchemaError: Invalid Schema`. Which does not contain the information why the schema is invalid (please see the screenshot below)

![image](https://github.com/hyperjump-io/json-schema/assets/63534268/e39cd6f3-b0db-4575-a458-260a3d3be894)

Sorry, if I have missed something from the docs. But Is there any option which can give some information about why the schema is invalid?

**Comment by jdesrosiers** [comment]
`InvalidSchemaError` has a property called "output" that contains the validation results you're looking for. See the "Change the schema validation output format" section in the [Output Formats](https://github.com/hyperjump-io/json-schema?tab=readme-ov-file#output-formats) documentation for an example.

**Comment by JeelRajodiya** [comment]
Thank you
